### ISSUE TITLE
Any chance of uploading a Realsense recording somewhere?

### ISSUE THREAD

**Issue by andybak** [keijiro/Rsvfx#1]
I don't have access to a Realsense but I'd love to try out this project. As the Realsense Unity component has 3 modes: live, record and playback - I'm guessing I could get a good idea of how it works if I could use a recorded file.

Is there any chance of uploading one somewhere? It's going to be too big for Github but I'd be happy to provide hosting for it if that helps.

**Comment by keijiro** [comment]
Unfortunately no, it's not possible due to a bug in the RealSense SDK; Unity Editor crashes when trying to use the recorder functionality. I guess it requires a significant amount of time to fix the problem, so I stop looking into it in details.

I'm closing this issue now. Please notify me if you really need it. I have to reschedule some other tasks for it.
